**DAV PRACTICALS**

In [1]:
import numpy as np
import pandas as pd

***Q1***

In [2]:
height = {'Boys':[72, 68, 70, 69, 74], 'Girls':[63, 65, 69, 62, 61]}
result = [{'Boy':bh, 'Girl':gh} for bh, gh in zip(height['Boys'], height['Girls'])]
result

[{'Boy': 72, 'Girl': 63},
 {'Boy': 68, 'Girl': 65},
 {'Boy': 70, 'Girl': 69},
 {'Boy': 69, 'Girl': 62},
 {'Boy': 74, 'Girl': 61}]

***Q2***

In [31]:
#Part(a)
arr = np.random.randint(1,100,size=(3,5))
mean = arr.mean(axis=1)
var = arr.var(axis=1)
sd = arr.std(axis=1)
print("Part (a)")
print("Original array : \n", arr)
print("Mean = ", mean)
print("Standard Deviation = ", sd)
print("Variation = ", var)
print()

#Part(b)
print("Part (b)")
B=np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
Sorted_indices = B.argsort()
print("Original Array = ", B)
print("Sorted_Indices = ", Sorted_indices)
print()

#Part(c)
print("Part (c)")
m = int(input("Enter the value of m : "))
n = int(input("Enter the value of n : "))
arr2 = np.random.randint(1, 50, size=(m, n))
print("m x n Array : \n", arr2)
print("Shape = ", arr2.shape)
print("Type = ", type(arr2))
print("Data Type = ", arr2.dtype)
arr3 = arr2.reshape(n, m)
print()
print("n x m Array : \n", arr3)

#Part(d)

Part (a)
Original array :  [[23 86 56  6 54]
 [56 83 12 44 54]
 [98 59 38 65 22]]
Mean =  [45.  49.8 56.4]
Standard Deviation =  [27.88548009 22.89454083 25.81937257]
Variation =  [777.6  524.16 666.64]

Part (b)
Original Array =  [56 48 22 41 78 91 24 46  8 33]
Sorted_Indices =  [8 2 6 9 3 7 1 0 4 5]

Part (c)


Enter the value of m :  4
Enter the value of n :  5


m x n Array = 
 [[16 26 29  1 47]
 [ 5 30 39 43 46]
 [25 32 27 33 33]
 [ 1 14 29 37 11]]
Shape =  (4, 5)
Type =  <class 'numpy.ndarray'>
Data Type =  int32

n x m Array = 
 [[16 26 29  1]
 [47  5 30 39]
 [43 46 25 32]
 [27 33 33  1]
 [14 29 37 11]]


***Q3***

In [51]:
p = 0.10 #setting the probability
df = pd.DataFrame(np.random.randint(1, 100, size=(50, 3)), columns=['C1', 'C2', 'C3'])
mask = np.random.choice([True, False], size=df.shape, p=[p,1-p])
new_df = df.mask(mask)
print(new_df)

#part(a)
print("Part (a)")
null_count = new_df.isnull().sum()
print("Null_Count = ",null_count)
print()

#part(b)
print("Part (b)")
new_df2 = new_df.dropna(axis=1, thresh = df.shape[0] - 5)
print(new_df2)
print()

#part(c)
print("Part (c)")
max_sum_row = new_df.sum(axis=1).idxmax()
new_df = new_df.drop(max_sum_row)
print()

#part(d)
print("Part (d)")
new_df3 = new_df.sort_values(by = 'C1')
print(new_df)
print()

#part(e)
print("Part (e)")
new_df4 = new_df.drop_duplicates(subset='C1')
print(new_df4)
print()

#part(f)
print("Part (f)")
correlation = new_df['C1'].corr(new_df['C2'])
covariance = new_df['C2'].cov(new_df['C3'])
print("Correlation between C1 and C2 = ", correlation)
print()
print("Covarinace between C2 and C3 = ", covariance)
print()

#part (g)
print("Part (g)")
z_scores = (new_df - new_df.mean()) / new_df.std()
outliers = (z_scores > 3) | (z_scores < -3)
new_df = new_df[~outliers.any(axis=1)]
print("\ng. DataFrame after removing rows with outliers:")
print(new_df)

#part(h)
new_df['Column2_bins'] = pd.cut(new_df['C2'], bins=5)
print("\nh. DataFrame with second column discretized into 5 bins:")
print(df)

    C1    C2    C3
0   15  37.0  92.0
1   28   2.0  72.0
2   42  92.0  35.0
3    3  42.0  62.0
4   67  26.0  92.0
5   50  56.0  69.0
6   48  54.0  74.0
7   87  14.0  30.0
8   55  72.0  24.0
9   56   1.0  72.0
10  13  72.0  20.0
11  17  38.0  20.0
12  64  49.0   4.0
13  78   9.0  54.0
14  17  23.0   6.0
15  64  49.0  66.0
16  24  40.0  76.0
17  64  30.0  30.0
18  78  76.0  31.0
19   5  47.0  35.0
20  81  65.0  24.0
21  81  37.0  43.0
22  18  10.0  88.0
23  76  89.0  44.0
24  46  21.0   3.0
25  21  36.0   2.0
26  63  43.0  62.0
27  49  28.0  78.0
28  96  93.0  10.0
29  19  16.0   NaN
30  27  34.0   2.0
31  29  11.0  42.0
32  40   2.0  58.0
33  24  15.0   4.0
34  20  58.0   1.0
35  91  93.0  34.0
36  52   8.0  83.0
37  24  28.0  66.0
38   1  93.0  74.0
39  22  62.0  19.0
40  39  43.0  43.0
41  60   NaN  52.0
42  47  70.0  85.0
43  14  86.0  33.0
44  64   7.0  22.0
45  43  40.0  90.0
46  69  65.0  67.0
47   6   NaN   3.0
48  52  59.0  60.0
49  77  76.0  90.0
Null_Count =  C1    0
C2    2
C